/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.ecoretools;

import org.eclipse.emf.ecoretools.AbstractAleRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AleRuntimeModule extends AbstractAleRuntimeModule {
}
