/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.ecoretools;

import org.eclipse.emf.ecoretools.AleStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AleStandaloneSetup extends AleStandaloneSetupGenerated {
  public static void doSetup() {
    new AleStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
