/**
 * Copyright (c) 2017 Inria and Obeo.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Inria - initial API and implementation
 * 
 * generated by Xtext 2.12.0
 */
package org.eclipse.emf.ecoretools.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.ecoretools.AleRuntimeModule;
import org.eclipse.emf.ecoretools.AleStandaloneSetup;
import org.eclipse.emf.ecoretools.ide.AleIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AleIdeSetup extends AleStandaloneSetup {
  @Override
  public Injector createInjector() {
    AleRuntimeModule _aleRuntimeModule = new AleRuntimeModule();
    AleIdeModule _aleIdeModule = new AleIdeModule();
    return Guice.createInjector(Modules2.mixin(_aleRuntimeModule, _aleIdeModule));
  }
}
