/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.ale.repl

import org.eclipse.xtext.formatting.IFormatter
import fr.inria.diverse.ale.repl.formatting.Visitor2replFormatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Visitor2replRuntimeModule extends AbstractVisitor2replRuntimeModule {
	
	override Class<? extends IFormatter> bindIFormatter() {
		Visitor2replFormatter
	}
	
}
